import { injectable, inject } from 'tsyringe';
import { UserRepository } from '../../repositories';
import { PasswordResetService } from '../../services/PasswordResetService';
import { config } from '../../config';
import { logger, NotFoundError } from '../../utils';
import { IUseCase } from '../interfaces/IUseCase';

/**
 * Use Case: Generate password reset link by Professor
 * 
 * Responsibilities:
 * - Validate that the requester is a Professor (handled by middleware usually, but good to check)
 * - Find user by ID
 * - Revoke previous reset tokens
 * - Create new reset token
 * - Return the reset link
 */
@injectable()
export class GenerateResetLinkUseCase implements IUseCase<string, { resetLink: string }> {
    constructor(
        @inject(UserRepository) private userRepository: UserRepository,
        @inject(PasswordResetService) private passwordResetService: PasswordResetService
    ) { }

    async execute(userId: string): Promise<{ resetLink: string }> {
        try {
            const user = await this.userRepository.findById(userId);

            if (!user) {
                throw new NotFoundError('User not found', 'USER_NOT_FOUND');
            }

            // Revoke previous tokens
            await this.passwordResetService.revokeAllUserTokens(user.id);

            // Create new token (expires in 1 hour)
            const resetToken = await this.passwordResetService.createResetToken(user.id, 1);

            const resetUrl = `${config.frontendUrl}/reset-senha?token=${resetToken}`;

            logger.info('[PASSWORD] Reset link generated by professor', {
                targetUser: user.email,
                userId: user.id
            });

            return {
                resetLink: resetUrl
            };
        } catch (error) {
            logger.error('[PASSWORD] Error generating reset link by professor', {
                userId,
                error: error instanceof Error ? error.message : 'Unknown error'
            });
            throw error;
        }
    }
}
